services:
  - type: web
    name: phone-suggester-api
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/phone-suggester-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: PORT
        value: 8080
    healthCheckPath: /api/v1/phones
    autoDeploy: true
    plan: free 